apiVersion: apps/v1
kind: Deployment
metadata:
   name: flaskapi-deployment
   namespace: mlflowonkube
spec:
   template:
      spec:
         containers:
         -  name: flaskapi
            image: localhost:32000/mlflow-flask:registry
