apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pv-claim
   namespace: {{namespace}}
   labels:
      app: mysql
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: {{mysql.storage}}
