apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{namespace}}
spec:
  type: LoadBalancer
  ports:
  - port: {{mysql.port}}
    targetPort: {{mysql.port}}
    name: http
  selector:
    app: mysql
