apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nexus-local-pv-claim
   namespace: {{namespace}}
   labels:
      app: nexus
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
