apiVersion: v1
kind: PersistentVolume
metadata:
   name: mlflow-pv-volume
   namespace: {{namespace}}
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: {{mlflow.storage}}
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: {{mlflow.mountPath}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mlflow-pv-claim
   namespace: {{namespace}}
   labels:
      app: mlflowserver
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: {{mlflow.storage}}
   volumeName: mlflow-pv-volume
