apiVersion: v1
kind: Service
metadata:
   name: nexus-service
   namespace: mlflowonkube
spec:
   type: NodePort
   ports:
   -  port: 8081
      nodePort: 30001
      protocol: TCP
      name: http
   -  port: 5000
      nodePort: 30002
      protocol: TCP
      name: docker
   selector:
      app: nexus
