kind: PersistentVolume
apiVersion: v1
metadata:
   name: nexus-local-pv
   namespace: {{namespace}}
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 2Gi
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: {{nexsus.mountPath}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nexus-local-pv-claim
   namespace: {{namespace}}
   labels:
      app: nexus
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 2Gi
