apiVersion: batch/v1
kind: Job
metadata:
   name: LogisticRegression
   namespace: mlflowonkube
spec:
   ttlSecondsAfterFinished: 100
   backoffLimit: 1
   template:
      spec:
         containers:
         -  name: LogisticRegression
            image: localhost:32000/mlflow-on-kubernetes-docker
            command:
            - python train.py --alpha {alpha} --l1-ratio {l1_ratio}
         resources:
            limits:
               memory: 512Mi
            requests:
               memory: 256Mi
         restartPolicy: Never
