apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pv-claim
   namespace: mlflowonkube
   labels:
      app: mysql
spec:
   storageClassName: longhorn
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
