apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-pv-volume
   namespace: mlflowonkube
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 1Gi
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: /mnt/db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pv-claim
   namespace: mlflowonkube
   labels:
      app: mysql
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
   volumeName: mysql-pv-volume