apiVersion: v1
kind: Service
metadata:
   name: flaskapi-service
   namespace: mlflowonkube
spec:
   selector:
      app: flaskapi
   type: NodePort
   ports:
   -  protocol: TCP
      port: 9791
      targetPort: 9791
      nodePort: 30091
