apiVersion: apps/v1
kind: Deployment
metadata:
   name: flaskapi-deployment
   namespace: {{namespace}}
   labels:
      app: flaskapi
spec:
   replicas: 1
   selector:
      matchLabels:
         app: flaskapi
   template:
      metadata:
         labels:
            app: flaskapi
      spec:
         containers:
         -  name: flaskapi
            image: {{flask.mountPath}}
            env:
            -  name: MODEL_PATH
               value: /mnt/mlflow/0/{{flask.run_id}}/artifacts/model
            ports:
            -  containerPort: 9791
            volumeMounts:
            -  name: mlflow-persistent-storage
               mountPath: {{flask.mountPath}}
         imagePullSecrets:
         -  name: regcred
         volumes:
         -  name: mlflow-persistent-storage
            persistentVolumeClaim:
               claimName: mlflow-pv-claim
