apiVersion: v1
kind: PersistentVolume
metadata:
   name: mlflow-pv-volume
   namespace: mlflowonkube
   labels:
      type: local
spec:
   storageClassName: manual
   capacity:
      storage: 1Gi
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: /mnt/mlflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mlflow-pv-claim
   namespace: mlflowonkube
   labels:
      app: mlflowui
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
   volumeName: mlflow-pv-volume