apiVersion: apps/v1
kind: Deployment
metadata:
   name: nexus-deployment
   namespace: {{namespace}}
spec:
   selector:
      matchLabels:
         app: nexus
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: nexus
      spec:
         containers:
         -  image: {{nexsus.docker_image}}
            imagePullPolicy: Always
            name: nexus
            ports:
            -  containerPort: 8081
            -  containerPort: 5000
            volumeMounts:
            -  mountPath: {{nexsus.mountPath}}
               name: nexus-data-volume
         volumes:
         -  name: nexus-data-volume
            persistentVolumeClaim:
               claimName: nexus-local-pv-claim
