apiVersion: apps/v1
kind: Deployment
metadata:
   name: mlflowserver
   namespace: {{namespace}}
spec:
   selector:
      matchLabels:
         app: mlflowserver
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: mlflowserver
      spec:
         containers:
         -  name: mlflowserver
            image: {{mlflow.docker_image}}
            ports:
            -  containerPort: {{mlflow.port}}
               name: mlflowserver
            volumeMounts:
            -  name: mlflow-persistent-storage
               mountPath: {{mlflow.mountPath}}
         volumes:
         -  name: mlflow-persistent-storage
            persistentVolumeClaim:
               claimName: mlflow-pv-claim
