apiVersion: v1
kind: Service
metadata:
   name: mlflowserver
   namespace: {{namespace}}
spec:
   type: NodePort
   ports:
   -  port: {{mlflow.port}}
      protocol: TCP
      nodePort: {{mlflow.nodePort}}
      name: http
   selector:
      app: mlflowserver
