apiVersion: v1
kind: Service
metadata:
   name: mlflowserver
   namespace: mlflowonkube
spec:
   type: NodePort
   ports:
   -  port: 5002
      protocol: TCP
      nodePort: 30035
      name: http
   selector:
      app: mlflowserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mlflowserver
   namespace: mlflowonkube
spec:
   selector:
      matchLabels:
         app: mlflowserver
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: mlflowserver
      spec:
         containers:
         -  image: localhost:32000/mlflow-server:registry
            name: mlflowserver
            ports:
            -  containerPort: 5002
               name: mlflowserver
            volumeMounts:
            -  name: mlflow-persistent-storage
               mountPath: /mnt/mlflow
         volumes:
         -  name: mlflow-persistent-storage
            persistentVolumeClaim:
               claimName: mlflow-pv-claim
