apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: {{namespace}}
  labels:
    name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: ellerbrock/alpine-mysql-client
    command: ["sleep", "1000"]