apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{namespace}}
spec:
  type: NodePort
  ports:
  - port: {{mysql.port}}
    nodePort: {{mysql.nodePort}}
    name: http
  selector:
    app: mysql
