apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mlflow-pv-claim
   namespace: {{namespace}}
   labels:
      app: mlflowserver
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: {{mlflow.storage}}
