apiVersion: v1
kind: Service
metadata:
   name: nexus3-service
   namespace: mlflowonkube
spec:
   type: NodePort
   ports:
   -  port: 8081
      targetPort: 8081
      nodePort: 30001
      protocol: TCP
      name: http
   -  port: 8082
      targetPort: 8082
      nodePort: 30002
      protocol: TCP
      name: docker
   selector:
      app: nexus3
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nexus3-deployment
   namespace: mlflowonkube
spec:
   selector:
      matchLabels:
         app: nexus3
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: nexus3
      spec:
         containers:
         -  image: sonatype/nexus3
            imagePullPolicy: Always
            name: nexus3
            resources:
               limits:
                  memory: 2Gi
                  cpu: 1000m
               requests:
                  memory: 1Gi
                  cpu: 500m
            ports:
            -  containerPort: 8081
            -  containerPort: 8082
            volumeMounts:
            -  mountPath: /sonatype-work
               name: nexus-data-volume
         volumes:
         -  name: nexus-data-volume
            emptyDir: {}